---
apiVersion: v1
kind: Deployment
metadata:
  name: helloworld-deployment
namespace: tommy
spec:
  replicas: 2
  template:
  metadata:
    labels:
      app: helloworld
  spec:
    containers:
    - name: k8s-demo
      image: tommy/demo
      ports:
      - name: nodejs-port
        containerPort: 3000
