---
apiVersion: v1
kind: Pod
metadata:
  name: helloworld-deployment
spec:
  replicas: 2
  template:
  metadata:
    labels:
      app: helloworld
  spec:
    containers:
    - name: k8s-test
      image: gcr.io/google-samples/node-hello:1.0
      ports:
      - name: nodejs-port
        containerPort: 3000
